#!/bin/sh
# River session startup. Keep this file executable.

riverctl background-color 0x1e1e2e
riverctl border-color-focused 0xcba6f7
riverctl border-color-unfocused 0x45475a
riverctl border-width 2
riverctl default-layout rivertile
riverctl focus-follows-cursor normal
riverctl set-repeat 50 300

# Applications and desktop services.
riverctl spawn 'waybar'
riverctl spawn 'dunst'
riverctl spawn 'wl-paste --type text --watch cliphist store'
riverctl spawn 'wl-paste --type image --watch cliphist store'
riverctl spawn 'swww-daemon'
riverctl spawn 'sh -c "[ -x \"$HOME/.config/river/autostart\" ] && \"$HOME/.config/river/autostart\""'

# Modifiers and common commands.
mod=Mod4
term='kitty'
launcher='rofi -show drun -show-icons'

riverctl map normal $mod Return spawn "$term"
riverctl map normal $mod D spawn "$launcher"
riverctl map normal $mod Q close
riverctl map normal $mod F toggle-fullscreen
riverctl map normal $mod V toggle-float
riverctl map normal $mod+Shift E exit
riverctl map normal None Print spawn 'grim -g "$(slurp)" - | swappy -f -'
riverctl map normal $mod Escape spawn 'sh "$HOME/.config/river/powermenu"'

# Focus and move windows.
riverctl map normal $mod H focus-view left
riverctl map normal $mod J focus-view down
riverctl map normal $mod K focus-view up
riverctl map normal $mod L focus-view right
riverctl map normal $mod+Shift H move left
riverctl map normal $mod+Shift J move down
riverctl map normal $mod+Shift K move up
riverctl map normal $mod+Shift L move right
riverctl map normal $mod Space zoom

# Resize mode.
riverctl declare-mode resize
riverctl map normal $mod R enter-mode resize
riverctl map resize None Escape enter-mode normal
riverctl map resize H resize horizontal -100
riverctl map resize J resize vertical 100
riverctl map resize K resize vertical -100
riverctl map resize L resize horizontal 100

# Workspaces/tags: River uses bitmask tags. 1..9 map to tags 1..9.
for i in 1 2 3 4 5 6 7 8 9; do
    tags=$((1 << (i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Shift $i set-view-tags $tags
    riverctl map normal $mod+Control $i toggle-focused-tags $tags
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags

done
riverctl map normal $mod Tab focus-previous
riverctl map normal $mod+Shift Tab send-to-urgent
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Media keys.
riverctl map normal None XF86AudioRaiseVolume spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
riverctl map normal None XF86AudioLowerVolume spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
riverctl map normal None XF86AudioMute spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
riverctl map normal None XF86MonBrightnessUp spawn 'brightnessctl set 5%+'
riverctl map normal None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'

# Rules and layout.
riverctl rule-add -app-id '.*' ssd
riverctl rule-add -title 'Picture-in-Picture' float
rivertile -view-padding 6 -outer-padding 6 &
